apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joomla
  namespace: joomla
spec:
  releaseName: joomla
  chart:
    spec:
      chart: joomla
      sourceRef:
        kind: HelmRepository
        name: joomla
  interval: 50m
  install:
    remediation:
      retries: 3
